# Generated by Django 6.0 on 2025-12-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=100)),
                ('part_type', models.CharField(choices=[('cpu', 'CPU'), ('gpu', 'GPU'), ('motherboard', 'Motherboard'), ('ram', 'RAM'), ('storage', 'Storage'), ('psu', 'Power Supply'), ('case', 'Case')], db_index=True, max_length=20)),
                ('specs', models.JSONField()),
                ('msrp', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['part_type'], name='parts_part_part_ty_f18953_idx'), models.Index(fields=['msrp'], name='parts_part_msrp_c88ca8_idx')],
            },
        ),
    ]
